#!/bin/bash

# TODO logging

inotifywait -m ~/ -e create -e moved_to |
    while read dir action file; do
        echo "The file '$file' appeared in directory '$dir' via '$action'"

        if [[ "$file" == *.tar.xz* ]]; then

            dir=null

            case "$file" in
            "martials_no")
                dir=home
                ;;
            "api_martials_no")
                dir=api
                ;;
            "nextcloud")
                dir=nextcloud
                ;;
            esac

            if [ dir != null ]; then # TODO transaction, all or nothing
                echo y | sudo rm /var/www/"$dir/*"

                sudo mv "$file" /var/www/"$dir"
                sudo tar -xf /var/www/"${dir}/$file"

                echo yes | sudo rm /var/www/"${dir}/$file"
            fi

        fi

    done
